SSERVICES_EXT_VERSION = 1.0
SSERVICES_EXT_SOURCE = local
SSERVICES_EXT_SITE = $(BR2_PACKAGE_SSERVICES_EXT_SITE)
SSERVICES_EXT_SITE_METHOD = local
SSERVICES_EXT_INSTALL_STAGING = YES
SSERVICES_EXT_DEPENDENCIES = optee_client_ext host-python-cryptography
SSERVICES_EXT_SDK = $(BR2_PACKAGE_SSERVICES_EXT_SDK)
SSERVICES_EXT_CONF_OPTS = -DOPTEE_TEST_SDK=$(SSERVICES_EXT_SDK)

define SSERVICES_EXT_BUILD_TAS
	echo Building $(@D)/ta/Makefile && \
		$(MAKE) CROSS_COMPILE="$(shell echo $(BR2_PACKAGE_SSERVICES_EXT_CROSS_COMPILE))" \
		O=out TA_DEV_KIT_DIR=$(SSERVICES_EXT_SDK) \
		PYTHON3=$(HOST_DIR)/bin/python3 \
		$(TARGET_CONFIGURE_OPTS) -C $(dir $(@D)/ta/Makefile) all
endef

define SSERVICES_EXT_INSTALL_TAS
	mkdir -p $(TARGET_DIR)/lib/optee_armtz && \
		$(INSTALL) -v -p  --mode=444 \
		--target-directory=$(TARGET_DIR)/lib/optee_armtz $(@D)/ta/out/*.ta
endef

SSERVICES_EXT_POST_BUILD_HOOKS += SSERVICES_EXT_BUILD_TAS
SSERVICES_EXT_POST_INSTALL_TARGET_HOOKS += SSERVICES_EXT_INSTALL_TAS

$(eval $(cmake-package))
